server:
  port: 8080

spring:
  redis:
    host: 192.168.45.110
    port: 6379
    database: 0
    timeout: 180000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 0

