server:
  port: 80


spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    #    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    #    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: hystrixOrder80.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
feign:
  hystrix:
    enabled: true


